### ISSUE TITLE
Plotting without y error

### ISSUE THREAD

**Issue by AmeliaFord353** [DeaglanBartlett/ESR#15]
Plotting script isn't working when not supplied y errors (which is the case when using poisson likelihood class)

**Comment by DeaglanBartlett** [comment]
Fixed in d8332955e0e14b3e154290ff0d1202333bb1bb78. If `yerr` is defined in the `likelihood` class, then the points are plotted with errorbars. If not, then the errorbars are omitted, but the data are still plotted:

https://github.com/DeaglanBartlett/ESR/blob/d8332955e0e14b3e154290ff0d1202333bb1bb78/esr/fitting/plot.py#L117-L120
