### ISSUE TITLE
get_pred() exception handling in likelihood class

### ISSUE THREAD

**Issue by AmeliaFord353** [DeaglanBartlett/ESR#27]
In the likelihood class in likelihood.py, there are errors being caused when trying to determine y values for functions, such as divide by zero. These are being produced in get_pred(). Possibly the code needs an exception handling if y cannot be calculated, or a process to drop the problematic functions altogether?

**Comment by DeaglanBartlett** [comment]
Can I check whether these are actually being raised as errors or whether you are just getting things printed such as `0.0 cannot be raised to a negative power`? If the latter, then this is just from printing the exception (but still catching it) in `fitting.test_all`. I have removed this print statement in the branch associated with this issue. If the former, can you give me an example of where this causes an error rather than just printing the warning?

**Comment by DeaglanBartlett** [comment]
Having just looked at the output file you sent me, it appears that the issue was being raised in `match` and not `test_all`. I've now put the try-except statement you suggested in. Please can you check whether this has fixed your issue?

**Comment by AmeliaFord353** [comment]
Hi Deaglan,

Thank you - I'll run this now. I don't know if it will be completed by the time by the meeting at 3pm but I should at least have enough of an output to see if any errors are being thrown.

Thanks,
________________________________

**Comment by AmeliaFord353** [comment]
Yes, thank you!
