### ISSUE TITLE
generating redundant osc_math functions?

### ISSUE THREAD

**Issue by Jaysen-Ma** [DeaglanBartlett/ESR#31]
I ran with the following code

import esr.generation.duplicate_checker
runname = 'osc_maths'
comp = 3
esr.generation.duplicate_checker.main(runname, comp)

and obtained the following list from the unique_equations_3.txt

1) sin(sin(x))
2) a0 + x
3) sin(1/x)
4) a0 - x
5) a0*x
6) 1/sin(a0)
7) a0
8) x
9) 2*x
10) pow(Abs(a0),x)
11) a0/x
12) 1
13) 0
14) x**2
15) sin(sin(a0))
16) 1/sin(x)
17) Abs(a0)
18) pow(x,x)
19) sin(a0)
20) pow(x,a0)

I) I am wondering are equations 
5 & 9 (a0 could be 2?),
6 & 7 (both are constant that could range from 0 - inf?)
12 & 13 (should they fall into equation 7) a0 ?)
14 & 20, 
15 & 19 
repetitive? 

II) When I declare comp = 3, does it generate all functions with complexity up to 3 or only functions with complexity 3?
equation 7, 8, 12, 13, 17, 19 have complexity 1 or 2 but this list is missing sin(x) which is complexity 2.

**Comment by DeaglanBartlett** [comment]
Hi! Thanks for checking this. The duplicate checking procedure is not perfect in ESR (some parts are hand-coded by identifying common patterns to be checked for) so it's nice to know which ones slip through! 

For question (I), I think I am currently happy with this list (until Issue #32 is complete), because:

- 5&9, 12&13&7, 14&20: I agree that some of these are special cases of others, so could in fact be merged. To do this, I would want to implement a procedure which explicitly checks whether a parameter can be turned into an integer, since how these are handled in e.g. the description length is different to floats. I've therefore added a new issue (#32) to do this. We already have a procedure which does this to see if any parameter can be made equal to zero, but not yet for integers. When this is complete, I agree that we would want to remove these duplicates.
- 6&7, 15&19: I have been deliberately conservative when identifying functions of constants since the range of allowed values may not always match. In this case Eq 6 can only take values <= -1 or >= 1 (since sin(a0) cannot be outside [-1,1], its reciprocal cannot be within this range), so it is not entirely equivalent to Eq 7. Similarly, Eq 19 can take values between +/-1, but Eq 15 can only be between +/- sin(1), so they are not quite equivalent. 

For question (II), when you do comp=3, it will only do complexity 3 functions. You will have to separately run complexity 1 and 2. Sometimes functions appear which seem simpler than the complexity you are considering, but this is usually due to mathematical simplifications of a longer tree. All the trees generated are given in the trees_*.txt files so you can see how these seemingly simpler functions were generated. See PR #29 for a look at how we (now) deal with functions which were seen at lower complexity.

Hope that clears things up!
